### ISSUE TITLE
ROOT_PATH

### ISSUE THREAD

**Issue by DanielFatkic** [aXenDeveloper/ips-app-advanced-serverlist#1]
Hey,
Following part needs to be changed tomusw `IPS\Application::getRootPath() ` https://github.com/aXenDeveloper/ips-app-serverlist/blob/e20517094502a32417a303ab5d9c191ab8177579/sources/Servers/Servers.php#L117``
See also https://invisioncommunity.com/developers/docs/invision-community-45/summary-of-changes-r189/ ;)

**Comment by DanielFatkic** [comment]
I would also move the stuff to the sources directory instead of using the interface directory for this!

**Comment by aXenDeveloper** [comment]
> I would also move the stuff to the sources directory instead of using the interface directory for this!

I moved the icons to this folder, but I'd rather keep the GameQ library in this folder.
