### ISSUE TITLE
[Idea] Custom request provider

### ISSUE THREAD

**Issue by Nerus87** [aXenDeveloper/ips-app-advanced-serverlist#10]
I'm in a situation that I can handle the queries to the servers myself because I have the opportunity to build a web API service that will handle my all-game servers and provide this information based on the last state of the query.
It will prevent some security lack in the context of the requests sent directly from the web and providing information asap.
So my idea will be to provide a link to API service in app settings, so in this case, we should get a schema for the requests.

**Comment by aXenDeveloper** [comment]
Interesting idea, but it requires a lot of code work. Perhaps such an option will appear, but I don't know when I do it.
