### ISSUE TITLE
Brakująca kolumna w tabeli mysql

### ISSUE THREAD

**Issue by xdbx1021** [aXenDeveloper/ips-app-advanced-serverlist#13]
Po aktualizacji w której został dodany custom connect link brakuje kolumny w mysql:
Błąd przy edytowaniu serwera:
![Screenshot_6](https://user-images.githubusercontent.com/59399620/119038338-4d2cd380-b9b3-11eb-80a2-21366b9c4bde.png)

**Comment by aXenDeveloper** [comment]
Uruchom narzędzie do rozwiązywania problemów w zakładce "Support".
Tam będzie komunikat o błędzie z bazą danych i tam będziesz mógł naprawić błąd.

**Comment by xdbx1021** [comment]
Dzięki za szybką reakcję.
