### ISSUE TITLE
[Idea] Custom Game Option

### ISSUE THREAD

**Issue by FliesWithWind** [aXenDeveloper/ips-app-advanced-serverlist#15]
Since it's hard to cover all Steam games, how about adding an option for Custom Steam Game?

The logic for Steam server query is same for most of Steam games. 

User would choose Steam query type and would have an option to upload the icon

**Comment by aXenDeveloper** [comment]
Maybe in 2.0.0 version including with custom API and custom buttons ༼ つ ◕_◕ ༽つ
