### ISSUE TITLE
Server Adding issue

### ISSUE THREAD

**Issue by drk200** [aXenDeveloper/ips-app-advanced-serverlist#16]
whenever I try to add new server it throws me this error

Error: Call to undefined method IPS\Application::getRootPath() (0)
#0 /opt/bitnami/wordpress/forum/system/Node/Model.php(3164): IPS\axenserverlist\_Servers->postSaveForm()
#1 /opt/bitnami/wordpress/forum/system/Node/Controller.php(413): IPS\Node\_Model->saveForm()
#2 /opt/bitnami/wordpress/forum/system/Dispatcher/Controller.php(85): IPS\Node\_Controller->form()
#3 /opt/bitnami/wordpress/forum/system/Node/Controller.php(62): IPS\Dispatcher\_Controller->execute()
#4 /opt/bitnami/wordpress/forum/applications/axenserverlist/modules/admin/servers/servers.php(36): IPS\Node\_Controller->execute()
#5 /opt/bitnami/wordpress/forum/system/Dispatcher/Dispatcher.php(152): IPS\axenserverlist\modules\admin\servers\_servers->execute()
#6 /opt/bitnami/wordpress/forum/admin/index.php(14): IPS\_Dispatcher->run()
#7 {main}

**Comment by aXenDeveloper** [comment]
What do you have php and IPS version?

**Comment by drk200** [comment]
php version 7.4 
ips version 4.4

**Comment by aXenDeveloper** [comment]
See [requirements](https://github.com/aXenDeveloper/ips-app-advanced-serverlist#%EF%B8%8F-requirements) for app.
Min IPS 4.5

**Comment by drk200** [comment]
I downloaded 1.1.0(Older Version) of your plugin
1.1.0

**Comment by aXenDeveloper** [comment]
This app never use IPS 4.4.
You must have IPS 4.5 or higher.
