### ISSUE TITLE
No option to create new server

### ISSUE THREAD

**Issue by TheGreyRaven** [aXenDeveloper/ips-app-advanced-serverlist#19]
Hi!
So I just installed your application and when I read your readme I noticed that I have no "Advanced Server List" button in the AdminCP as can be seen here: https://i.imgur.com/vbbYWm6.png

I'm running 4.6.4 and PHP 7.4, I also have the latest download of this plugin directly from Github.
Any ideas what might be wrong?
I have no other plugins installed, just this and your theme.

**Comment by aXenDeveloper** [comment]
![image](https://user-images.githubusercontent.com/58148176/126870934-193f8da0-8a60-4968-939e-6bf04d66671b.png)
