### ISSUE TITLE
[Feature Request] Better Buttons

### ISSUE THREAD

**Issue by BlackYuzia** [aXenDeveloper/ips-app-advanced-serverlist#20]
Hi there. 
First what I want to say - **thx for that great app**.

I think better remove hard coded buttons like "Forum", "Stats" etc.

Why do not create a tab with fields for buttons like:

```
[Button Name] [Button Translate Word] [Button Class Select] [Button Icon Select]
```

### Example 
![image](https://user-images.githubusercontent.com/25010528/134930648-752f0126-d252-4c2c-b490-d4815db87f71.png)

Then, you can create any count of buttons with custom name, class and icons (by press "add new button"). 
That is better like a few hardcoded buttons without name and icons change feature.

**Comment by aXenDeveloper** [comment]
Maybe in 2.0.0 version including with custom API ༼ つ ◕_◕ ༽つ

**Comment by aXenDeveloper** [comment]
After considering the proposal, the option will not be implemented.
Too many dependencies to code for this option to work well.
