### ISSUE TITLE
[Feature Request] Discord Servers Users Info

### ISSUE THREAD

**Issue by BlackYuzia** [aXenDeveloper/ips-app-advanced-serverlist#22]
Hello, can you change a bit Discord Servers info?

In current time, you check online players of current discord server, so online servers is always the same as max online users.
You can choose mode for Discord Servers.

Modes:
- Show only online (100 online players)
- Show only total (200 total players)
- Show both (100 online / 200 total) 

Currently, you just show current online users of discord server:

![image](https://user-images.githubusercontent.com/25010528/138616346-7f59a02a-5d84-4a0e-a593-39f6b95e41b1.png)

That also means what you should create (MAYBE) API for menu and add points like:
![image](https://user-images.githubusercontent.com/25010528/138616423-3f3bf31e-7dea-4397-9711-a83b0b8f2b4a.png)

Most Online Players:  ....
Most Total Players: ...
Also, remove map and etc not used items...
Better to add API with any custom popup menu items and counters, buttons etc, I suppose.

**Comment by aXenDeveloper** [comment]
> In current time, you check online players of current discord server, so online servers is always the same as max online users.
You can choose mode for Discord Servers.

It often happens that these numbers change after API tests. I decided that the table will only show current users.
