### ISSUE TITLE
[BUG] Wrong Caching CSGO Servers Data

### ISSUE THREAD

**Issue by BlackYuzia** [aXenDeveloper/ips-app-advanced-serverlist#27]
Hi there, @aXenDeveloper 

In #24 PR from @CrazyHackGUT he would fix getting info from server by A2S queries.
But now, I get a bit different issue with that.

So, when I press refresh button
![image](https://user-images.githubusercontent.com/25010528/144668313-97026d59-4b51-4eeb-a628-3cf7893b0191.png)
after refresh data, all servers get valid status and valid data (like online, map and etc)
![image](https://user-images.githubusercontent.com/25010528/144668567-8aced97d-9e81-4f4e-ad5e-563922b4ddeb.png)

But, a few minutes later, that info return to "offline status". 
![image](https://user-images.githubusercontent.com/25010528/144668426-f2c5f3d3-223f-4fa2-b8a9-234ca19ac310.png)

This could be trouble in cache, but I don't sure. Could you test this bug in your own IPS? You could use any public IP:PORT of CSGO server, also I can give you IP:PORT of servers what I use.

**Comment by aXenDeveloper** [comment]
I can't reproduce this error.
Check servers by debug tool: https://github.com/aXenDeveloper/ips-app-advanced-serverlist-debug

**Comment by BlackYuzia** [comment]
Hmm, after using button "reload all servers" all is fine. I reopen or create new issue if I get the same trouble.

**Debug tool get all data successfully.**
