### ISSUE TITLE
GTA v multiplayer and categories

### ISSUE THREAD

**Issue by Cyr4x1337** [aXenDeveloper/ips-app-advanced-serverlist#30]
Please add please multiplayer for GTA V such as Rage:MP, Alt:V. it would be very nice for the community Grand Theft Auto, and so please add categories for servers. for example there is a project called "Project" they have 14 servers, and not to have to scroll through all 14 servers, wrap them in a category "Project Servers". Thank you for your attention.

**Comment by aXenDeveloper** [comment]
For GTA it is already implemented:
https://github.com/aXenDeveloper/ips-app-advanced-serverlist/blob/master/sources/GameQ/Protocols/Gta5m.php

About categories: Yes, I'll implement tis in the next major update.

**Comment by Cyr4x1337** [comment]
I could not figure out how to add servers alt:v and Rage:MP explain in more detail
