### ISSUE TITLE
Minecraft Bug

### ISSUE THREAD

**Issue by louanfontenele** [aXenDeveloper/ips-app-advanced-serverlist#4]
Hello, I'm trying to add a minecraft server, even putting the data correctly, it doesn't show the total number of players, now on this site, it shows the data correctly: https://mcsrvstat.us/server/minecraft.ggames.com.br:26532

Pics from my website:

![Screenshot_648](https://user-images.githubusercontent.com/2886066/112245390-8ead3680-8c2f-11eb-89df-3bf215479d4d.png)
![Screenshot_649](https://user-images.githubusercontent.com/2886066/112245392-8f45cd00-8c2f-11eb-81d9-8a7c2e510fa7.png)

**Comment by aXenDeveloper** [comment]
Hi,
The server is not answering any query.
Do you have any other IP?

Try add server here:
https://www.gametracker.com/search/minecraft/
