### ISSUE TITLE
 Errors when adding a server through a mod

### ISSUE THREAD

**Issue by KuroRaiken** [aXenDeveloper/ips-app-advanced-serverlist#45]
**Errors when adding a server through a mod**

```
Error: Call to undefined method IPS\Image::supportedExtensions() (0)
#0 C:\OpenServer\domains\freeplay\forum\system\Node\Controller.php(489): IPS\axenserverlist\_Mods->form()
#1 C:\OpenServer\domains\freeplay\forum\system\Node\Controller.php(388): IPS\Node\_Controller->_addEditForm()
#2 C:\OpenServer\domains\freeplay\forum\system\Dispatcher\Controller.php(90): IPS\Node\_Controller->form()
#3 C:\OpenServer\domains\lfreeplay\forum\system\Node\Controller.php(62): IPS\Dispatcher\_Controller->execute()
#4 C:\OpenServer\domains\freeplay\forum\applications\axenserverlist\modules\admin\servers\mods.php(35): IPS\Node\_Controller->execute()
#5 C:\OpenServer\domains\freeplay\forum\system\Dispatcher\Dispatcher.php(152): IPS\axenserverlist\modules\admin\servers\_mods->execute()
#6 C:\OpenServer\domains\freeplay\forum\admin\index.php(14): IPS\_Dispatcher->run()
#7 {main}

#0 C:\OpenServer\domains\freeplay\forum\init.php(995): IPS\_Log::log()
#1 [internal function]: IPS\IPS::exceptionHandler()
#2 {main}
```

**Comment by aXenDeveloper** [comment]
Check database tab in support page in `AdminCP`.

**Comment by KuroRaiken** [comment]
> Check database tab in support page in `AdminCP`.

The error disappeared after updating IPS to 4.6 but it doesn’t work on 4.5, can you check it yourself?

**Comment by aXenDeveloper** [comment]
So for IPS 4.5 doesn’t work, but for IPS 4.6 it works??

**Comment by KuroRaiken** [comment]
> То есть для IPS 4.5 не работает, а для IPS 4.6 работает??

Yes, everything works fine on 4.6, but on 4.5, when I go to add the server, it writes an unknown method.

**Comment by aXenDeveloper** [comment]
I tested this for IPS 4.5. For me it's working fine.

Check this topic: https://invisioncommunity.com/forums/topic/465989-php-gd-errors-after-updating-to-php-74-or-80/

**Comment by KuroRaiken** [comment]
> Я тестировал это для IPS 4.5. Для меня это работает нормально.
> 
> Проверьте эту тему: https://invisioncommunity.com/forums/topic/465989-php-gd-errors-after-updating-to-php-74-or-80/

I checked on 8.0 too, there was an error after that I decided to update IPS and the error was gone.

**Comment by aXenDeveloper** [comment]
With the upgrade to IPS 4.6.13 all my products below IPS 4.6 will lose support. This means that IPS 4.5 will no longer be supported.

I encourage you to update to the latest version.
