### ISSUE TITLE
Arma 3 Doesn't work

### ISSUE THREAD

**Issue by bladeeciti** [aXenDeveloper/ips-app-advanced-serverlist#5]
Hello,

I've setup my server correctly in the plugin like this.
[https://gyazo.com/a16b4a0616a3f1ee1babc7e0f2be0782](url)

It won't show players or any in-game information.

Gametracker works fine so query port is fine [https://www.gametracker.com/server_info/145.239.6.43:2302/](url)

Do you know how to fix this?

Thank you!

**Comment by aXenDeveloper** [comment]
Hi,
Try 145.239.6.43:2302 in the IP field.

**Comment by bladeeciti** [comment]
> Hi,
> Try 145.239.6.43:2302 in the IP field.

Thanks for the response.

I tried it but it still looks like this https://gyazo.com/8da3c679d2f3dab031b98245e6aa6c91

**Comment by bladeeciti** [comment]
Okay after further research It's a problem with having the Arma 3 Game selected, changing it to Dayz which uses the same query system works properly

**Comment by aXenDeveloper** [comment]
Hi,
Thanks for the reporting! This bug will be fixed in next released.

If you want replace this file: https://github.com/aXenDeveloper/ips-app-advanced-serverlist/blob/master/sources/GameQ/Protocols/Arma3.php
