### ISSUE TITLE
Garry's Mod servers go offline and require a manual refresh

### ISSUE THREAD

**Issue by mobbsti** [aXenDeveloper/ips-app-advanced-serverlist#59]
Hi, 

My GMOD sever constantly displays as "Offline" after a few page refreshes. 

After manually refreshing the server data in the settings it updates correctly but will break a few minutes later.

**Comment by aXenDeveloper** [comment]
What PHP version, app version and IPS version you use?
Enter the ip address.

**Comment by mobbsti** [comment]
Invision Community
Version 4.6.12.1

Running latest version

Caching
Cache Engine: None

No issues identified

Push Notifications
No issues identified

PHP
Version 7.4.30

No issues identified

Database
Version 5.7.38

No issues identified

**Comment by mcgibson-source** [comment]
I'm in the same boat. We are using php 8.1 and ips v4.7.0.
