### ISSUE TITLE
Samp Servers Display Offline

### ISSUE THREAD

**Issue by igdiogo** [aXenDeveloper/ips-app-advanced-serverlist#60]
I tried in every way, but the San Andreas server keeps showing offline.
Andress IP: 144.217.39.72:7777
PHP Version IPS: 7.4.2.8

**Comment by aXenDeveloper** [comment]
> PHP Version IPS: 7.4.2.8

what?

**Comment by igdiogo** [comment]
Server samp "San Andreas Multiplayer" don't work. 
When putting the IP it can't return the server.
