### ISSUE TITLE
Serwer TS3

### ISSUE THREAD

**Issue by Blaqus** [aXenDeveloper/ips-app-advanced-serverlist#63]
Witam, posiadam problem z tabelką serwerów. Mianowicie pokazuje że serwer jest offline. Problem jest tylko z serwerem TeamSpeak.
Port oraz IP poprawne.

**Comment by aXenDeveloper** [comment]
Jakie dane przychodzą z serwera? Użyj wbudowanego debugera, aby zobaczyć co jest nie tak.

**Comment by Blaqus** [comment]
#0 /home/host941358/domains/just4frag.pl/public_html/applications/axenserverlist/modules/admin/servers/servers.php(100): IPS\_Log::log('array (\n  5 => ...', '(aXen) Advanced...')
#1 /home/host941358/domains/just4frag.pl/public_html/system/Dispatcher/Controller.php(90): IPS\axenserverlist\modules\admin\servers\_servers->debug()
#2 /home/host941358/domains/just4frag.pl/public_html/system/Node/Controller.php(69): IPS\Dispatcher\_Controller->execute()
#3 /home/host941358/domains/just4frag.pl/public_html/applications/axenserverlist/modules/admin/servers/servers.php(114): IPS\Node\_Controller->execute()
#4 /home/host941358/domains/just4frag.pl/public_html/system/Dispatcher/Dispatcher.php(153): IPS\axenserverlist\modules\admin\servers\_servers->execute()
#5 /home/host941358/domains/just4frag.pl/public_html/admin/index.php(13): IPS\_Dispatcher->run()
#6 {main}

**Comment by aXenDeveloper** [comment]
To nie jest odpowiedź z debugera, a jego ścieżka uruchamiania.

**Comment by Blaqus** [comment]
array (
  5 => 
  array (
    'gq_address' => '[178.217.188.31](https://l.messenger.com/l.php?u=http%3A%2F%2F178.217.188.31%2F&h=AT2xe9LjXlZ5ZgE6-4Y3CKlhzxOrZLngqH_UMbesdttxZJ_WU1ViGWv57xuoe2mTS2n1qSuZM6BX0sso5LPvUvPRJ_AzUN7L9bfKMB27arG6PIALmTbGOGgYrS8PaHEkPI1N7w)',
    'gq_dedicated' => NULL,
    'gq_hostname' => NULL,
    'gq_joinlink' => 'ts3server://[178.217.188.31?port=9987](http://178.217.188.31/?port=9987)',
    'gq_maxplayers' => NULL,
    'gq_name' => 'Teamspeak 3',
    'gq_numplayers' => NULL,
    'gq_online' => false,
    'gq_password' => NULL,
    'gq_port_client' => 9987,
    'gq_port_query' => 9987,
    'gq_protocol' => 'teamspeak3',
    'gq_transport' => 'tcp',
    'gq_type' => 'teamspeak3',
    'players' => 
    array (
    ),
    'teams' => 
    array (
    ),
  ),
)

**Comment by aXenDeveloper** [comment]
'gq_online' => false,``
Z tych logów wynika że tabelka nie może nawiązać połączenia z serwerem.
Sprawdź poprawność danych do połączenia oraz przeczytaj dokładnie instrukcje co do TS3 w pliku `readme.md`.

**Comment by Blaqus** [comment]
Wszystko jest uzupełnione poprawnie. Guest posiada uprawnienia tak jak w radme jest napisane.

**Comment by aXenDeveloper** [comment]
To musisz skontaktować się z administratorem Twojego serwera.
Tutaj moja rola się kończy, ponieważ nie jest to błąd tabelki.
