### ISSUE TITLE
[Idea] Server visibility

### ISSUE THREAD

**Issue by Nerus87** [aXenDeveloper/ips-app-advanced-serverlist#7]
Hello, I have an infrastructure problem with this plugin.

My IPS Board works on a machine that provides an internet connection (and doing the redirections for games servers) to another machine that provides game servers. So game servers are visible on to the local IP Address for the app.

Server List App will do the queries directly to Lan but the **link in the server table** will be pointing to the **local address, not external**. 
In this case, clients will not be able to join the server because they will be connecting to the local address like 192.168.1.2:27015.

I guess the simplest form will be to add a custom link connection field in the server configuration.
Will you be able to add a new option for handling this case?

**Comment by aXenDeveloper** [comment]
Interesting proposition. I will work on adding this option.
