### ISSUE TITLE
Design 

### ISSUE THREAD

**Issue by Destructor** [aXenDeveloper/ips-app-advanced-serverlist#73]
Hello,

Would it be possible to add a way to change the appearance on the serverlist, for example the server name gets compacted and it doesn't make the server page look pretty 😄

between the number of players and the logos on the right there is a gap and it's a shame

![image](https://github.com/aXenDeveloper/ips-app-advanced-serverlist/assets/1570770/72a67c7c-8b95-4756-a562-2fb2c8368914)
Thanks in advance

**Comment by aXenDeveloper** [comment]
Hi,
You can disable "Get name from server and display?" option in server settings.

**Comment by Destructor** [comment]
even deactivating it remains the same

**Comment by aXenDeveloper** [comment]
You can change appearance the table by CSS.

**Comment by Destructor** [comment]
I don't see any css file linked to the server list, or do I need to add something?

**Comment by aXenDeveloper** [comment]
You have to write own code in `custom.css`.

**Comment by Destructor** [comment]
not possible to add it directly in the module configuration ?
Not knowing enough css on ipboard

**Comment by aXenDeveloper** [comment]
Not in IPS4, maybe in IC5.
