### ISSUE TITLE
[Problem] Refreshing and caching

### ISSUE THREAD

**Issue by Nerus87** [aXenDeveloper/ips-app-advanced-serverlist#9]
There are some problems with refreshing, I didn't dig into the PHP code so I couldn't say what is the refresh threshold.
Nice will be if the user will be able to select how often requests need to be sent to the servers.
Maybe the problem is on the webserver with caching, but a good idea will be to add **do not cache** toggle in the settings?

**Comment by aXenDeveloper** [comment]
I cannot change the table update frequency in tasks. All I can do is create a setting that controls the number of requests to the server if it doesn't respond.

**Comment by Nerus87** [comment]
In my case is not the problem with server response (because is on the LAN directly) so the problem is not on the server-side.
It is very likely that nginx or even IPS Board lose connection with clients.

**Comment by aXenDeveloper** [comment]
I added this option:
![image](https://user-images.githubusercontent.com/58148176/118838418-f4334180-b8c5-11eb-9149-e1291e2fa40d.png)
I cannot manipulate the query frequency.
If you want to change the frequency of queries, download the dev IPS installation and files from the repository together with the dev folder and create your own query.
